# Generated by Django 4.2.5 on 2024-09-10 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escenarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('salarioMin', models.CharField(max_length=200)),
                ('salarioMax', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rotativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riesgo', models.CharField(max_length=200)),
                ('typeAsociado', models.CharField(max_length=200)),
                ('scoreMin', models.IntegerField()),
                ('scoreMax', models.IntegerField()),
                ('EA', models.FloatField()),
                ('NMV', models.FloatField()),
                ('plazo', models.IntegerField()),
                ('escenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rotativo.escenarios')),
            ],
        ),
    ]
