# Generated by Django 4.2.7 on 2024-09-13 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rotativo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsociadoRorativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('montoMax', models.CharField(max_length=200)),
                ('plazoMax', models.IntegerField()),
                ('requisitos', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='rotativo',
            name='scoreMax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rotativo',
            name='typeAsociado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rotativo.asociadororativo'),
        ),
    ]
