# Generated by Django 4.2.7 on 2024-09-13 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotativo', '0002_asociadororativo_alter_rotativo_scoremax_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AsociadoRorativo',
            new_name='AsociadoRotativo',
        ),
    ]
