# Generated by Django 4.2.5 on 2024-07-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0002_alter_tasascdat_tasa'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoSociales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FloatField()),
                ('usura', models.FloatField()),
                ('descuentos', models.FloatField()),
                ('techoEA', models.FloatField()),
                ('techoNMV', models.FloatField()),
                ('plazo', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='tasascooviahorro',
            name='tasa',
            field=models.FloatField(),
        ),
    ]
