# Generated by Django 4.2.5 on 2024-07-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0003_nosociales_alter_tasascooviahorro_tasa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nosociales',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
