# Generated by Django 4.2.5 on 2024-07-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0004_alter_nosociales_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAsociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
