# Generated by Django 4.2.5 on 2024-07-12 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0005_typeasociado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasasNoSociales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxScore', models.IntegerField()),
                ('minScore', models.IntegerField()),
                ('fg', models.FloatField()),
                ('plazo', models.IntegerField()),
                ('garantia', models.CharField(max_length=200)),
                ('piso', models.FloatField()),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controls.typeasociado')),
            ],
        ),
    ]
