# Generated by Django 4.2.5 on 2024-07-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0006_tasasnosociales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fidelizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('porcentaje', models.FloatField()),
                ('tasa6', models.FloatField()),
                ('tasa12', models.FloatField()),
                ('tasa24', models.FloatField()),
                ('tasa36', models.FloatField()),
                ('tasa48', models.FloatField()),
                ('tasa60', models.FloatField()),
                ('tasa72', models.FloatField()),
                ('plazoMax', models.IntegerField()),
                ('garantia', models.CharField(max_length=500)),
            ],
        ),
    ]
