# Generated by Django 4.2.5 on 2024-07-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0007_fidelizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sociales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tasa6', models.FloatField()),
                ('tasa12', models.FloatField()),
                ('tasa24', models.FloatField()),
                ('tasa36', models.FloatField()),
                ('tasa48', models.FloatField(default=0)),
                ('tasa60', models.FloatField(default=0)),
                ('tasa72', models.FloatField(default=0)),
                ('tasa84', models.FloatField(default=0)),
                ('plazoMax', models.IntegerField()),
            ],
        ),
    ]
