# Generated by Django 4.2.5 on 2024-07-25 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0009_asociadotype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjustesCDAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montoMin', models.CharField(max_length=300)),
                ('montoMax', models.CharField(max_length=300)),
                ('ajuste', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AjustesCooviahorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montoMin', models.CharField(max_length=300)),
                ('montoMax', models.CharField(max_length=300)),
                ('ajuste', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MaximoAjusteAporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MaximoAjusteCDAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MaximoAjusteCooviahorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MaximoAjustePlazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MaximoAjusteScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AjustesScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoreMin', models.IntegerField()),
                ('scoreMax', models.IntegerField()),
                ('ajuste', models.IntegerField()),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controls.typeasociado')),
            ],
        ),
        migrations.CreateModel(
            name='AjustesPlazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plazoMin', models.IntegerField()),
                ('plazoMax', models.IntegerField()),
                ('ajuste', models.IntegerField()),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controls.typeasociado')),
            ],
        ),
        migrations.CreateModel(
            name='AjustesAportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aporteMin', models.IntegerField()),
                ('aporteMax', models.IntegerField()),
                ('ajuste', models.IntegerField()),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controls.typeasociado')),
            ],
        ),
    ]
