# Generated by Django 4.2.5 on 2024-07-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0010_ajustescdat_ajustescooviahorro_maximoajusteaporte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajustesaportes',
            name='aporteMax',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ajustesaportes',
            name='aporteMin',
            field=models.CharField(max_length=200),
        ),
    ]
