# Generated by Django 4.2.5 on 2024-09-09 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0013_alter_maximoajuste_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ajustesaportes',
            name='asociado',
        ),
        migrations.DeleteModel(
            name='AjustesCDAT',
        ),
        migrations.DeleteModel(
            name='AjustesCooviahorro',
        ),
        migrations.RemoveField(
            model_name='ajustesplazo',
            name='asociado',
        ),
        migrations.RemoveField(
            model_name='ajustesscore',
            name='asociado',
        ),
        migrations.DeleteModel(
            name='AsociadoType',
        ),
        migrations.DeleteModel(
            name='Fidelizacion',
        ),
        migrations.DeleteModel(
            name='MaximoAjuste',
        ),
        migrations.DeleteModel(
            name='NoSociales',
        ),
        migrations.DeleteModel(
            name='Sociales',
        ),
        migrations.DeleteModel(
            name='TasasCDAT',
        ),
        migrations.DeleteModel(
            name='TasasCooviahorro',
        ),
        migrations.RemoveField(
            model_name='tasasnosociales',
            name='perfil',
        ),
        migrations.DeleteModel(
            name='AjustesAportes',
        ),
        migrations.DeleteModel(
            name='AjustesPlazo',
        ),
        migrations.DeleteModel(
            name='AjustesScore',
        ),
        migrations.DeleteModel(
            name='TasasNoSociales',
        ),
        migrations.DeleteModel(
            name='TypeAsociado',
        ),
    ]
