# Generated by Django 4.2.5 on 2024-09-09 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjustesCDAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montoMin', models.CharField(max_length=300)),
                ('montoMax', models.CharField(max_length=300)),
                ('ajuste', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AjustesCooviahorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montoMin', models.CharField(max_length=300)),
                ('montoMax', models.CharField(max_length=300)),
                ('ajuste', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MaximoAjuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AjustesScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoreMin', models.IntegerField()),
                ('scoreMax', models.IntegerField()),
                ('ajuste', models.IntegerField()),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credito.typeasociado')),
            ],
        ),
        migrations.CreateModel(
            name='AjustesPlazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plazoMin', models.IntegerField()),
                ('plazoMax', models.IntegerField()),
                ('ajuste', models.IntegerField()),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credito.typeasociado')),
            ],
        ),
        migrations.CreateModel(
            name='AjustesAportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aporteMin', models.CharField(max_length=200)),
                ('aporteMax', models.CharField(max_length=200)),
                ('ajuste', models.IntegerField()),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credito.typeasociado')),
            ],
        ),
    ]
