# Generated by Django 4.2.5 on 2024-09-09 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsociadoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fidelizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('porcentaje', models.FloatField()),
                ('tasa6', models.FloatField()),
                ('tasa12', models.FloatField()),
                ('tasa24', models.FloatField()),
                ('tasa36', models.FloatField()),
                ('tasa48', models.FloatField()),
                ('tasa60', models.FloatField()),
                ('tasa72', models.FloatField()),
                ('plazoMax', models.IntegerField()),
                ('garantia', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='NoSociales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('usura', models.FloatField()),
                ('descuentos', models.FloatField()),
                ('techoEA', models.FloatField()),
                ('techoNMV', models.FloatField()),
                ('plazo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sociales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tasa6', models.FloatField()),
                ('tasa12', models.FloatField()),
                ('tasa24', models.FloatField()),
                ('tasa36', models.FloatField()),
                ('tasa48', models.FloatField(default=0)),
                ('tasa60', models.FloatField(default=0)),
                ('tasa72', models.FloatField(default=0)),
                ('tasa84', models.FloatField(default=0)),
                ('plazoMax', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeAsociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TasasNoSociales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxScore', models.IntegerField()),
                ('minScore', models.IntegerField()),
                ('fg', models.FloatField()),
                ('plazo', models.IntegerField()),
                ('garantia', models.CharField(max_length=200)),
                ('piso', models.FloatField()),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credito.typeasociado')),
            ],
        ),
    ]
