# Generated by Django 4.2.5 on 2024-12-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrossimulacionescreditos',
            name='createdBy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registrossimulacionescreditos',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrossimulacionescreditos',
            name='dateafi',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registrossimulacionescreditos',
            name='dateborn',
            field=models.CharField(max_length=100),
        ),
    ]
