# Generated by Django 4.2.5 on 2024-12-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_registrossimulacionescreditos_createdby_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSimulacionesCdat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameAsociado', models.CharField(max_length=100)),
                ('typeCdat', models.CharField(max_length=100)),
                ('tasa', models.FloatField()),
                ('value', models.CharField(max_length=100)),
                ('plazo', models.IntegerField()),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='registrossimulacionescreditos',
            name='seniority',
            field=models.CharField(max_length=100),
        ),
    ]
