# Generated by Django 4.2.1 on 2024-12-26 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_alter_registrossimulacionescreditos_seniority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrossimulacionescreditos',
            name='linea',
        ),
    ]
