# Generated by Django 4.2.7 on 2024-12-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_remove_registrossimulacionescreditos_linea'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSimulacionRotativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameAsociado', models.CharField(max_length=100)),
                ('document', models.IntegerField()),
                ('dateAfiliacion', models.CharField(max_length=100)),
                ('typeAsociado', models.CharField(max_length=100)),
                ('typeContract', models.CharField(blank=True, max_length=100, null=True)),
                ('pagaduria', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('descuentos', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('monto', models.CharField(max_length=100)),
            ],
        ),
    ]
