# Generated by Django 4.2.7 on 2025-01-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_registrosimulacionrotativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSimulacionCooviahorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameAsociado', models.CharField(max_length=100)),
                ('tipoCooviahorro', models.CharField(max_length=100)),
                ('valorAhorroMensual', models.CharField(max_length=100)),
                ('plazo', models.IntegerField()),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='registrosimulacionrotativo',
            name='createdBy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registrosimulacionrotativo',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
