# Generated by Django 4.2.5 on 2024-09-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TasasCooviahorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('amountMin', models.CharField(max_length=100)),
                ('termMin', models.IntegerField()),
                ('tasa', models.FloatField()),
            ],
        ),
    ]
