# Generated by Django 4.2.5 on 2024-09-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TasasCDAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('since', models.CharField(max_length=100)),
                ('until', models.CharField(max_length=100)),
                ('amountsince', models.IntegerField()),
                ('amountuntil', models.IntegerField()),
                ('tasa', models.FloatField()),
            ],
        ),
    ]
